# Generated by Django 6.0.6 on 2026-06-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brokerage_user_brokerage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='insurers.branch')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
            ],
            options={
                'ordering': ('branch__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('document', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['brokerage', 'name'], name='insurers_br_brokera_6a3be1_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('brokerage', 'name'), name='unique_branch_name_per_brokerage'),
        ),
        migrations.AddIndex(
            model_name='coverage',
            index=models.Index(fields=['brokerage', 'name'], name='insurers_co_brokera_a52d15_idx'),
        ),
        migrations.AddConstraint(
            model_name='coverage',
            constraint=models.UniqueConstraint(fields=('brokerage', 'branch', 'name'), name='unique_coverage_name_per_branch'),
        ),
        migrations.AddIndex(
            model_name='insurer',
            index=models.Index(fields=['brokerage', 'name'], name='insurers_in_brokera_9dd555_idx'),
        ),
        migrations.AddIndex(
            model_name='insurer',
            index=models.Index(fields=['brokerage', 'document'], name='insurers_in_brokera_504112_idx'),
        ),
        migrations.AddConstraint(
            model_name='insurer',
            constraint=models.UniqueConstraint(fields=('brokerage', 'name'), name='unique_insurer_name_per_brokerage'),
        ),
    ]
