# Generated by Django 6.0.6 on 2026-06-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0002_brokerage_user_brokerage'),
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('vehicle', 'Automóvel'), ('property', 'Imóvel'), ('fleet', 'Frota'), ('travel', 'Viagem'), ('life', 'Vida'), ('other', 'Outro')], default='other', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covered_items', to='insurers.branch')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covered_items', to='clients.client')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['brokerage', 'name'], name='policies_co_brokera_2080b7_idx'), models.Index(fields=['brokerage', 'identifier'], name='policies_co_brokera_8f2998_idx')],
            },
        ),
    ]
