# Generated by Django 6.0.6 on 2026-06-25 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0002_brokerage_user_brokerage'),
        ('insurers', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('approved', 'Aprovada'), ('rejected', 'Recusada'), ('converted', 'Convertida em Apólice')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('premium_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('insured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.branch')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='clients.client')),
                ('coverages', models.ManyToManyField(blank=True, related_name='proposals', to='insurers.coverage')),
                ('covered_items', models.ManyToManyField(blank=True, related_name='proposals', to='policies.covereditem')),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.insurer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('premium_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('insured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.branch')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client')),
                ('coverages', models.ManyToManyField(blank=True, related_name='policies', to='insurers.coverage')),
                ('covered_items', models.ManyToManyField(blank=True, related_name='policies', to='policies.covereditem')),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.insurer')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policies.proposal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['brokerage', 'status'], name='policies_pr_brokera_307ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['brokerage', 'client'], name='policies_pr_brokera_91a3b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(condition=models.Q(('proposal_number', ''), _negated=True), fields=('brokerage', 'proposal_number'), name='unique_proposal_number_per_brokerage'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['brokerage', 'status'], name='policies_po_brokera_e7462b_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['brokerage', 'client'], name='policies_po_brokera_776e80_idx'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('policy_number', ''), _negated=True), fields=('brokerage', 'policy_number'), name='unique_policy_number_per_brokerage'),
        ),
    ]
