# Generated by Django 6.0.6 on 2026-06-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brokerage_user_brokerage'),
        ('policies', '0002_proposal_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsement_number', models.CharField(blank=True, max_length=20)),
                ('endorsement_type', models.CharField(choices=[('inclusion', 'Inclusão'), ('exclusion', 'Exclusão'), ('alteration', 'Alteração'), ('cancellation', 'Cancelamento')], default='alteration', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endorsements', to='policies.policy')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['brokerage', 'policy'], name='policies_en_brokera_b86bf9_idx')],
            },
        ),
    ]
