# Generated by Django 6.0.6 on 2026-06-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brokerage_user_brokerage'),
        ('policies', '0002_proposal_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em Andamento'), ('settled', 'Liquidado'), ('rejected', 'Recusado')], default='open', max_length=20)),
                ('occurrence_date', models.DateField(blank=True, null=True)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_settled', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
                ('covered_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.covereditem')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['brokerage', 'status'], name='claims_clai_brokera_25009b_idx'), models.Index(fields=['brokerage', 'policy'], name='claims_clai_brokera_48c335_idx')],
            },
        ),
    ]
