# Generated by Django 6.0.6 on 2026-06-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brokerage_user_brokerage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_type', models.CharField(choices=[('individual', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='individual', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('document', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['brokerage', 'name'], name='clients_cli_brokera_704036_idx'), models.Index(fields=['brokerage', 'document'], name='clients_cli_brokera_dcca01_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document', ''), _negated=True), fields=('brokerage', 'document'), name='unique_client_document_per_brokerage')],
            },
        ),
    ]
