# Generated by Django 6.0.6 on 2026-06-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brokerage_user_brokerage'),
        ('policies', '0003_endorsement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renewal_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('renewed', 'Renovado'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('previous_end_date', models.DateField(blank=True, null=True)),
                ('new_start_date', models.DateField(blank=True, null=True)),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('premium_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='policies.policy')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['brokerage', 'status'], name='renewals_re_brokera_238c53_idx'), models.Index(fields=['brokerage', 'policy'], name='renewals_re_brokera_f972cd_idx')],
            },
        ),
    ]
