from django.urls import path

from .views import (
    CoveredItemCreateView,
    CoveredItemDeleteView,
    CoveredItemDetailView,
    CoveredItemListView,
    CoveredItemUpdateView,
    EndorsementCreateView,
    EndorsementDeleteView,
    EndorsementDetailView,
    EndorsementListView,
    EndorsementUpdateView,
    GeneratePolicyView,
    PolicyCreateView,
    PolicyDeleteView,
    PolicyDetailView,
    PolicyListView,
    PolicyUpdateView,
    ProposalCreateView,
    ProposalDeleteView,
    ProposalDetailView,
    ProposalListView,
    ProposalUpdateView,
)


urlpatterns = [
    path('covered-items/', CoveredItemListView.as_view(), name='covered_item_list'),
    path('covered-items/create/', CoveredItemCreateView.as_view(), name='covered_item_create'),
    path('covered-items/<int:pk>/', CoveredItemDetailView.as_view(), name='covered_item_detail'),
    path('covered-items/<int:pk>/edit/', CoveredItemUpdateView.as_view(), name='covered_item_update'),
    path('covered-items/<int:pk>/delete/', CoveredItemDeleteView.as_view(), name='covered_item_delete'),
    path('proposals/', ProposalListView.as_view(), name='proposal_list'),
    path('proposals/create/', ProposalCreateView.as_view(), name='proposal_create'),
    path('proposals/<int:pk>/', ProposalDetailView.as_view(), name='proposal_detail'),
    path('proposals/<int:pk>/edit/', ProposalUpdateView.as_view(), name='proposal_update'),
    path('proposals/<int:pk>/delete/', ProposalDeleteView.as_view(), name='proposal_delete'),
    path('proposals/<int:pk>/generate-policy/', GeneratePolicyView.as_view(), name='generate_policy'),
    path('policies/', PolicyListView.as_view(), name='policy_list'),
    path('policies/create/', PolicyCreateView.as_view(), name='policy_create'),
    path('policies/<int:pk>/', PolicyDetailView.as_view(), name='policy_detail'),
    path('policies/<int:pk>/edit/', PolicyUpdateView.as_view(), name='policy_update'),
    path('policies/<int:pk>/delete/', PolicyDeleteView.as_view(), name='policy_delete'),
    path('endorsements/', EndorsementListView.as_view(), name='endorsement_list'),
    path('endorsements/create/', EndorsementCreateView.as_view(), name='endorsement_create'),
    path('endorsements/<int:pk>/', EndorsementDetailView.as_view(), name='endorsement_detail'),
    path('endorsements/<int:pk>/edit/', EndorsementUpdateView.as_view(), name='endorsement_update'),
    path('endorsements/<int:pk>/delete/', EndorsementDeleteView.as_view(), name='endorsement_delete'),
]
