# Generated by Django 6.0.6 on 2026-06-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brokerage_user_brokerage'),
        ('policies', '0003_endorsement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[('received', 'Recebida'), ('passed', 'Repassada')], default='received', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.brokerage')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='policies.policy')),
            ],
            options={
                'ordering': ('-commission_date', '-created_at'),
                'indexes': [models.Index(fields=['brokerage', 'commission_type'], name='commissions_brokera_d0f229_idx'), models.Index(fields=['brokerage', 'status'], name='commissions_brokera_fc6275_idx'), models.Index(fields=['brokerage', 'policy'], name='commissions_brokera_818707_idx')],
            },
        ),
    ]
